#! /usr/bin/env bash

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd $DIR

python -m SimpleHTTPServer

